#!/bin/sh

xrandr --dpi 120							# Set DPI. User may want to use a larger number for larger screens.
xset r rate 300 50 &
xset s on && xset s 100 && xss-lock slock &
#[ -x /usr/bin/gpg-agent ] && eval "$(/usr/bin/gpg-agent --daemon)" &
xwallpaper --stretch $XDG_DATA_HOME/wallpapers/nord_mountains.jpg &	# set the background with the `setbg` script

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="sxhkd picom unclutter pipewire joystickwake"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
